feat: auto created shared config
Unirep/create-unirep-app pull request #6
Opened 2022-11-25 21:12 UTC by vimwitch

2022-11-29 02:50 UTC, vivianjeng requested changes
This should be changed to `userContext.reputation.posRep` as well

https://github.com/Unirep/create-unirep-app/blob/9a677b4000897cd04772e4d5d2966de1d66af3e6/packages/frontend/src/Home.jsx#L43

2022-11-29 02:50 UTC, vivianjeng commented on packages/frontend/src/Home.jsx
> -                setTotalNegRep(Number(negRep)+ Number(totalNegRep))
Here I mean to show the current epoch reputation (but not received)
and after transition, the user can check if all reputation are received in the new epoch

so current rep = current epoch rep (not received) + previous epoch rep (received)
the rep which is received is shown in 

https://github.com/Unirep/create-unirep-app/blob/9a677b4000897cd04772e4d5d2966de1d66af3e6/packages/frontend/src/Home.jsx#L43

2022-11-29 02:50 UTC, vivianjeng commented on packages/frontend/src/Home.jsx
> -                setTotalNegRep(Number(negRep)+ Number(totalNegRep))
or we need a better UI to let users know the rep what they request in the epoch will be processed next epoch.

2022-11-29 02:50 UTC, vivianjeng commented on packages/frontend/src/contexts/User.js
> +
we can remove this

2022-11-29 23:35 UTC, vimwitch commented
Right I took the auto user state transition code out, but the problem is this repo is intended to help people build attesters, not to be a product. It should be added back in as an optional thing.

2022-12-01 13:58 UTC, vivianjeng requested changes

2022-12-01 13:58 UTC, vivianjeng commented on packages/frontend/src/Home.jsx
> +              <div>Graffiti {userContext.graffiti?.toString()}</div>
```jsx
<div>Pos Rep {userContext.provableReputation.posRep?.toString()}</div> 
<div>Neg Rep {userContext.provableReputation.negRep?.toString()}</div> 
<div>Graffiti {userContext.provableReputation.graffiti?.toString()}</div>
```

2022-12-02 15:43 UTC, vivianjeng approved these changes
LGTM

2022-12-02 15:43 UTC, merged